webtalk_init -webtalk_dir C:\\CR_Projects\\Project\\Development\\FPGAMiner\\FPGAMiner.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-06-06 01:15:07" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "n46ofj6bkivn00btd7ej8s2afo" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_22" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1796 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.329 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1528241019387" -context "sdk\\\\hardware/1528241019387"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1528241019387"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1528241019387"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1528241019387"
webtalk_add_data -client sdk -key VivadoVersion -value "2017.4" -context "sdk\\\\hardware/1528241019387"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1528241019387"
webtalk_add_data -client sdk -key Device -value "7a100t" -context "sdk\\\\hardware/1528241019387"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1528241019387"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1528241019387"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1528241019387"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1528241019387"
webtalk_add_data -client sdk -key uid -value "1528241047307" -context "sdk\\\\bsp/1528241047307"
webtalk_add_data -client sdk -key hwid -value "1528241019387" -context "sdk\\\\bsp/1528241047307"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1528241047307"
webtalk_add_data -client sdk -key apptemplate -value "lwip_echo_server" -context "sdk\\\\bsp/1528241047307"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1528241047307"
webtalk_add_data -client sdk -key uid -value "1528241072062" -context "sdk\\\\application/1528241072062"
webtalk_add_data -client sdk -key hwid -value "1528241019387" -context "sdk\\\\application/1528241072062"
webtalk_add_data -client sdk -key bspid -value "1528241047307" -context "sdk\\\\application/1528241072062"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1528241072062"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1528241072062"
webtalk_add_data -client sdk -key apptemplate -value "lwip_echo_server" -context "sdk\\\\application/1528241072062"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1528241072062"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1528241072062"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1528241072062"
webtalk_add_data -client sdk -key projSize -value "273.35546875" -context "sdk\\\\application/1528241072062"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1528244107662"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1528244107662"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1528244107662"
webtalk_add_data -client sdk -key DebugCount -value "23" -context "sdk\\\\bsp/1528244107662"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1528244107662"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1528244107662"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1528244107662"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1528244107662"
webtalk_transmit -clientid 2032771030 -regid "" -xml C:\\CR_Projects\\Project\\Development\\FPGAMiner\\FPGAMiner.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\CR_Projects\\Project\\Development\\FPGAMiner\\FPGAMiner.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\CR_Projects\\Project\\Development\\FPGAMiner\\FPGAMiner.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
