set_property SRC_FILE_INFO {cfile:C:/CR_Projects/Project/Development/FPGAMiner/FPGAMiner.srcs/constrs_1/new/eth_ref_clk.xdc rfile:../../../FPGAMiner.srcs/constrs_1/new/eth_ref_clk.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:C:/CR_Projects/Project/Development/FPGAMiner/FPGAMiner.srcs/constrs_1/imports/Pins/Nexys4_Master.xdc rfile:../../../FPGAMiner.srcs/constrs_1/imports/Pins/Nexys4_Master.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D5 IOSTANDARD LVCMOS33} [get_ports eth_ref_clk]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_1/inst/clk_out1]]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[0]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[1]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[2]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[3]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[4]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[5]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[6]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[7]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[8]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[9]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[10]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[11]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[12]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[13]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[14]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[15]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[16]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[17]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[18]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[19]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[20]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[21]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[22]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[23]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[24]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[25]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[26]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[27]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[28]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[29]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[30]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[31]}]]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/microblaze_0_M0_AXIS_TDATA[0]} {design_1_i/microblaze_0_M0_AXIS_TDATA[1]} {design_1_i/microblaze_0_M0_AXIS_TDATA[2]} {design_1_i/microblaze_0_M0_AXIS_TDATA[3]} {design_1_i/microblaze_0_M0_AXIS_TDATA[4]} {design_1_i/microblaze_0_M0_AXIS_TDATA[5]} {design_1_i/microblaze_0_M0_AXIS_TDATA[6]} {design_1_i/microblaze_0_M0_AXIS_TDATA[7]} {design_1_i/microblaze_0_M0_AXIS_TDATA[8]} {design_1_i/microblaze_0_M0_AXIS_TDATA[9]} {design_1_i/microblaze_0_M0_AXIS_TDATA[10]} {design_1_i/microblaze_0_M0_AXIS_TDATA[11]} {design_1_i/microblaze_0_M0_AXIS_TDATA[12]} {design_1_i/microblaze_0_M0_AXIS_TDATA[13]} {design_1_i/microblaze_0_M0_AXIS_TDATA[14]} {design_1_i/microblaze_0_M0_AXIS_TDATA[15]} {design_1_i/microblaze_0_M0_AXIS_TDATA[16]} {design_1_i/microblaze_0_M0_AXIS_TDATA[17]} {design_1_i/microblaze_0_M0_AXIS_TDATA[18]} {design_1_i/microblaze_0_M0_AXIS_TDATA[19]} {design_1_i/microblaze_0_M0_AXIS_TDATA[20]} {design_1_i/microblaze_0_M0_AXIS_TDATA[21]} {design_1_i/microblaze_0_M0_AXIS_TDATA[22]} {design_1_i/microblaze_0_M0_AXIS_TDATA[23]} {design_1_i/microblaze_0_M0_AXIS_TDATA[24]} {design_1_i/microblaze_0_M0_AXIS_TDATA[25]} {design_1_i/microblaze_0_M0_AXIS_TDATA[26]} {design_1_i/microblaze_0_M0_AXIS_TDATA[27]} {design_1_i/microblaze_0_M0_AXIS_TDATA[28]} {design_1_i/microblaze_0_M0_AXIS_TDATA[29]} {design_1_i/microblaze_0_M0_AXIS_TDATA[30]} {design_1_i/microblaze_0_M0_AXIS_TDATA[31]}]]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T8 [get_ports {led[0]}]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V9 [get_ports {led[1]}]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R8 [get_ports {led[2]}]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T6 [get_ports {led[3]}]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T5 [get_ports {led[4]}]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T4 [get_ports {led[5]}]
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7 [get_ports {led[6]}]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U6 [get_ports {led[7]}]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4 [get_ports {led[8]}]
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U3 [get_ports {led[9]}]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V1 [get_ports {led[10]}]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R1 [get_ports {led[11]}]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P5 [get_ports {led[12]}]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1 [get_ports {led[13]}]
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports {led[14]}]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P2 [get_ports {led[15]}]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]
set_property src_info {type:XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L3 [get_ports {seg[0]}]
set_property src_info {type:XDC file:2 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N1 [get_ports {seg[1]}]
set_property src_info {type:XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L5 [get_ports {seg[2]}]
set_property src_info {type:XDC file:2 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L4 [get_ports {seg[3]}]
set_property src_info {type:XDC file:2 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K3 [get_ports {seg[4]}]
set_property src_info {type:XDC file:2 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M2 [get_ports {seg[5]}]
set_property src_info {type:XDC file:2 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L6 [get_ports {seg[6]}]
set_property src_info {type:XDC file:2 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M4 [get_ports dp]
set_property src_info {type:XDC file:2 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N6 [get_ports {an[0]}]
set_property src_info {type:XDC file:2 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M6 [get_ports {an[1]}]
set_property src_info {type:XDC file:2 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M3 [get_ports {an[2]}]
set_property src_info {type:XDC file:2 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N5 [get_ports {an[3]}]
set_property src_info {type:XDC file:2 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N2 [get_ports {an[4]}]
set_property src_info {type:XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N4 [get_ports {an[5]}]
set_property src_info {type:XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports {an[6]}]
set_property src_info {type:XDC file:2 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M1 [get_ports {an[7]}]
