set_property -dict {PACKAGE_PIN D5 IOSTANDARD LVCMOS33} [get_ports eth_ref_clk]



set_property MARK_DEBUG false [get_nets led_16bits_tri_i_0]
set_property MARK_DEBUG false [get_nets led_16bits_tri_i_1]
set_property MARK_DEBUG false [get_nets led_16bits_tri_i_10]
set_property MARK_DEBUG false [get_nets led_16bits_tri_i_11]
set_property MARK_DEBUG false [get_nets led_16bits_tri_i_12]
set_property MARK_DEBUG false [get_nets led_16bits_tri_i_13]
set_property MARK_DEBUG false [get_nets led_16bits_tri_i_14]
set_property MARK_DEBUG false [get_nets led_16bits_tri_i_15]
set_property MARK_DEBUG false [get_nets led_16bits_tri_i_2]
set_property MARK_DEBUG false [get_nets led_16bits_tri_i_3]
set_property MARK_DEBUG false [get_nets led_16bits_tri_i_4]
set_property MARK_DEBUG false [get_nets led_16bits_tri_i_5]
set_property MARK_DEBUG false [get_nets led_16bits_tri_i_6]
set_property MARK_DEBUG false [get_nets led_16bits_tri_i_7]
set_property MARK_DEBUG false [get_nets led_16bits_tri_i_8]
set_property MARK_DEBUG false [get_nets led_16bits_tri_i_9]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/microblaze_0_M0_AXIS_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[9]}]



create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_1/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[0]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[1]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[2]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[3]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[4]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[5]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[6]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[7]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[8]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[9]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[10]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[11]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[12]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[13]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[14]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[15]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[16]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[17]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[18]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[19]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[20]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[21]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[22]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[23]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[24]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[25]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[26]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[27]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[28]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[29]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[30]} {design_1_i/MinerCoprocessor_0_M00_AXIS_TDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/microblaze_0_M0_AXIS_TDATA[0]} {design_1_i/microblaze_0_M0_AXIS_TDATA[1]} {design_1_i/microblaze_0_M0_AXIS_TDATA[2]} {design_1_i/microblaze_0_M0_AXIS_TDATA[3]} {design_1_i/microblaze_0_M0_AXIS_TDATA[4]} {design_1_i/microblaze_0_M0_AXIS_TDATA[5]} {design_1_i/microblaze_0_M0_AXIS_TDATA[6]} {design_1_i/microblaze_0_M0_AXIS_TDATA[7]} {design_1_i/microblaze_0_M0_AXIS_TDATA[8]} {design_1_i/microblaze_0_M0_AXIS_TDATA[9]} {design_1_i/microblaze_0_M0_AXIS_TDATA[10]} {design_1_i/microblaze_0_M0_AXIS_TDATA[11]} {design_1_i/microblaze_0_M0_AXIS_TDATA[12]} {design_1_i/microblaze_0_M0_AXIS_TDATA[13]} {design_1_i/microblaze_0_M0_AXIS_TDATA[14]} {design_1_i/microblaze_0_M0_AXIS_TDATA[15]} {design_1_i/microblaze_0_M0_AXIS_TDATA[16]} {design_1_i/microblaze_0_M0_AXIS_TDATA[17]} {design_1_i/microblaze_0_M0_AXIS_TDATA[18]} {design_1_i/microblaze_0_M0_AXIS_TDATA[19]} {design_1_i/microblaze_0_M0_AXIS_TDATA[20]} {design_1_i/microblaze_0_M0_AXIS_TDATA[21]} {design_1_i/microblaze_0_M0_AXIS_TDATA[22]} {design_1_i/microblaze_0_M0_AXIS_TDATA[23]} {design_1_i/microblaze_0_M0_AXIS_TDATA[24]} {design_1_i/microblaze_0_M0_AXIS_TDATA[25]} {design_1_i/microblaze_0_M0_AXIS_TDATA[26]} {design_1_i/microblaze_0_M0_AXIS_TDATA[27]} {design_1_i/microblaze_0_M0_AXIS_TDATA[28]} {design_1_i/microblaze_0_M0_AXIS_TDATA[29]} {design_1_i/microblaze_0_M0_AXIS_TDATA[30]} {design_1_i/microblaze_0_M0_AXIS_TDATA[31]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
